### PR TITLE
Create sync-fork-workflow.yml

### PR DESCRIPTION
**Pull request by MohanRamSridhar**
## Description
This pull request adds a GitHub Actions workflow that automatically keeps our forked repository in sync with the upstream repository. The workflow is triggered whenever there is a push or merge to the main branch of the upstream repository, ensuring our fork stays up-to-date.

## Related Issue
#433 

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have added/updated relevant documentation (if needed)
- [X] I have tested the changes locally and they function as expected
- [X] I have ensured my code follows the project's coding standards

## Configuration Required:
1. Create a Personal Access Token (PAT) with repo permissions.
2. Add the PAT as a secret named PAT in the repository settings under Settings -> Secrets and variables -> Actions.

### CODE REVIEW

**Comment by MohanRamSridhar** [comment]
Can you please do the configuration changes that are required for this to run proper;y

**Comment by codewarnab** [comment]
ok i am testing it will let you know in 24 h

**Comment by codewarnab** [comment]
do one thing add it in the workflow folder where it should be and give the pr instead of txt it will not cause any issue if it has no upstream right ?

**Comment by MohanRamSridhar** [comment]
hey I wasn't able to catch it, you want to me rename the file to yml right?

**Comment by codewarnab** [comment]
> hey I wasn't able to catch it, you want to me rename the file to yml right?

yes and place it under .github/workflow folder where it should be to work properly

**Comment by MohanRamSridhar** [comment]
hey I have done the commits can you check it

**Comment by MohanRamSridhar** [comment]
hey and can you create a Peronal Access token with the permission for repo checked? and name it as PAT

**Comment by codewarnab** [comment]
> hey and can you create a Peronal Access token with the permission for repo checked? and name it as PAT, if not done already

will do it thanks for your pr

**Pull request merged**
