### PR TITLE
Resolving Issuee #522

### PR DESCRIPTION
**Pull request by Garima-149**
@itsekta I have also changed size of image.Please merge this.
Screenshot (107)

## Summary by CodeRabbit

- **New Features**
	- Added new routes for user navigation, including `/contact`, `/recovereds-page`, and `/happy-recoveries`.
	- Introduced a `ContactPage` allowing users to submit contact information and messages.
	- Enhanced `LandingPage` with a "Contact Us" button and improved form handling.

- **Styling Enhancements**
	- New styles introduced for input fields and containers to improve user experience and interface design.

- **Bug Fixes**
	- Resolved issues with form submission handling across components, ensuring better functionality.

### CODE REVIEW

**Comment by Garima-149** [comment]
@itsekta please review it.

**Comment by itsekta** [comment]
Hey @Garima-149, this branch have some conflicts please resolve them first

**Comment by Garima-149** [comment]
@itsekta I have resolved existing issues.

**Comment by itsekta** [comment]
Hey @Garima-149, 
The Contact Us page looks good, but I noticed that this PR contains changes to other components as well. Let's move all the form-related elements from the landing page into a dedicated Contact Us form component to make the code more manageable.

Also, you can create a new issue for the Contact Us form on the landing page instead of handling everything in a single issue.

**Comment by Garima-149** [comment]
Actually the change you are noticing is button element I added on landing page to help me navigate to contactUs page.Because I was asked to just creat contact Us page, and location of the page, will be decided by  project admin. That's why, I  made a button over there.

**Comment by itsekta** [comment]
@Garima-149 Ohk, I found the issue. The version differences in the GitHub review are because of different indentations.

**Review by itsekta — APPROVED** [review]
The changes looks good

**Comment by Garima-149** [comment]
But the PR is not merged yet. @itsekta

**Comment by itsekta** [comment]
It is blocked because this PR need 2 Reviewers approval, I have given mine wait for other mentors or PA review.

**Comment by Garima-149** [comment]
Is there any way to contact them?

**Comment by codewarnab** [comment]
#522

**Pull request merged**
