### PR TITLE
Responsive Design of Home Page

### PR DESCRIPTION
**Pull request by riya-rjha**
I have added a max height of the container which is thus disallowing the footer underneath to cover up the buttons. As and when the height resizes, the footer changes. 
Here's the final look in the desktop view: 
Screenshot (27)

#319  issue resolved

### CODE REVIEW

**Comment by codewarnab** [comment]
@riya-rjha   good job will be merged soon

**Review by codewarnab — APPROVED** [review]

**Comment by codewarnab** [comment]
@riya-rjha  wait before merging can you please add a screenshot of the mobile screen ?

**Comment by riya-rjha** [comment]
image
Screenshot (34)

Here are the two screenshots, for mobile screens it is working well, but when the height reduces till 660 pixels, the button overlaps the content.

**Comment by codewarnab** [comment]
Approved ! @rishicds

**Pull request merged**
