### PR TITLE
#252 improve from UI 

### PR DESCRIPTION
**Pull request by Priyal208**
## Description
I enhanced the look and feel of UI , as promised I made UI more appealing and beautiful made it look more professional. The older one was plain blank and basic. Here I have attached screenshots of how it looked earlier and how i completely changed it.

## Related Issue
Assigned to me under #252 

## Screenshots / GIFs (if applicable)
before-
Screenshot 2024-05-13 204147
after-
Screenshot 2024-05-13 205810
Screenshot 2024-05-13 205819

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
[Add any additional notes or context about the changes made]

### CODE REVIEW

**Comment by Priyal208** [comment]
@codewarnab Kindly review this!

**Comment by rishicds** [comment]
image

Hey @Priyal208 , please make the page responsive

**Comment by codewarnab** [comment]
> image
> 
> Hey @Priyal208 , please make the page responsive

no need merge it for responsiveness #261

**Comment by codewarnab** [comment]
@Priyal208  looks like  you havnt updated your branch for long please update your branch asap

**Comment by Priyal208** [comment]
> > image
> > Hey @Priyal208 , please make the page responsive
> 
> no need merge it for responsiveness #261 approved from my side fix the merge conflicts and good to go @Priyal208

okay sure

**Comment by Priyal208** [comment]
@codewarnab now pls check i have done so!

> @Priyal208 looks like you havnt updated your branch for long please update your branch asap

**Review by rishicds — APPROVED** [review]
LGTM!

**Pull request merged**
