### PR TITLE
Implemented Email verification system before user registration

### PR DESCRIPTION
**Pull request by atharvarekhawar**
## Description
I have used services like Email.js and npm package reat-otp-input to implement the email verification system before user registrstion

## Related Issue
#270 

## Screenshots / GIFs (if applicable)
https://github.com/Innovateninjas/Paws-frontend/assets/113119063/3e35677d-7a54-434e-a4f5-c475b402f051

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
I have also added steps for the setup of email.js in the contribution.md file.

### CODE REVIEW

**Comment by atharvarekhawar** [comment]
@codewarnab done with the required changes.

**Comment by atharvarekhawar** [comment]
@codewarnab any problem ? you have not merged the PR

**Comment by codewarnab** [comment]
> @codewarnab any problem ? you have not merged the PR

when i am locally cloning it and trying to run some depedecy (post css parsing error ) i will sit tonight try to fix it will merge soon

**Comment by atharvarekhawar** [comment]
> > @codewarnab any problem ? you have not merged the PR
> 
> when i am locally cloning it and trying to run some depedecy (post css parsing error ) i will sit tonight try to fix it will merge soon

ok fine 👍

**Comment by codewarnab** [comment]
hey we have just moved to vite from CRA can you fix the conflicts

**Pull request closed without merging**
