### PR TITLE
new logo added in the header of the website

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Description
new logo added in the header of the website
## Related Issue
issue #382 

## Screenshots / GIFs (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [ ] I have added/updated relevant documentation (if needed)
- [ ] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
[Add any additional notes or context about the changes made]

### CODE REVIEW

**Comment by codewarnab** [comment]
@RamakrushnaBiswal this pr contains the changes for background change it should only contain change for the favicon change . basically you  have to create new branch for each issue and give pr from it

**Comment by RamakrushnaBiswal** [comment]
@codewarnab what i need to do now ?
kindly help me

**Comment by RamakrushnaBiswal** [comment]
@codewarnab can i revert it ?

**Comment by codewarnab** [comment]
> @codewarnab can i revert it ?

close the pr create fresh new branch do neccesary changes to add new logo then give a pr

**Pull request closed without merging**
