### PR TITLE
Made the stats page of NGO Responsive  

### PR DESCRIPTION
**Pull request by dikshajaiswal855**
added a new div below the heading "STATISTICS" and applied tailwind to each div for making it responsive for small medium and large screen sizes.

[issue #282 ]
SS1
SS2
SS3

### CODE REVIEW

**Comment by rishicds** [comment]
please remove the blue background

**Comment by codewarnab** [comment]
> added a new div below the heading "STATISTICS" and applied tailwind to each div for making it responsive for small medium and large screen sizes.
> 
> [issue #282 ] SS1 SS2 SS3

you have to make the graphs/charts inside look good for  that you might need to login as an ngo . do it if you need any issue mention here

**Comment by dikshajaiswal855** [comment]
> please remove the blue background

sure @rishicds

**Comment by dikshajaiswal855** [comment]
> > added a new div below the heading "STATISTICS" and applied tailwind to each div for making it responsive for small medium and large screen sizes.
> > [issue #282 ] SS1 SS2 SS3
> 
> you have to make the graphs/charts inside look good(responsive) for that you might need to login as an ngo . do it if you need any issue mention here
ok @codewarnab

**Comment by dikshajaiswal855** [comment]
> > added a new div below the heading "STATISTICS" and applied tailwind to each div for making it responsive for small medium and large screen sizes.
> > [issue #282 ] SS1 SS2 SS3
> 
> you have to make the graphs/charts inside look good(responsive) for that you might need to login as an ngo . do it if you need any issue mention here

hey @codewarnab did you mean heat map of recoded animals.
Please clearify what I have to

**Comment by dikshajaiswal855** [comment]
image
is it ok @rishicds

**Comment by rishicds** [comment]
Yes but the graphs and stuff should also scale accordingly, look into that if possible @dikshajaiswal855

**Comment by dikshajaiswal855** [comment]
> Yes but the graphs and stuff should also scale accordingly, look into that if possible @dikshajaiswal855

yes sure

**Comment by dikshajaiswal855** [comment]
Screenshot (2250)

@rishicds please check

**Comment by rishicds** [comment]
The map is ok but the graph and other things are still small which does not look good on desktop view. @dikshajaiswal855

**Comment by dikshajaiswal855** [comment]
> The map is ok but the graph and other things are still small which does not look good on desktop view. @dikshajaiswal855

ok I got it I have to fix report

**Comment by dikshajaiswal855** [comment]
@rishicds now please tell is it ok

Screenshot (2251)

**Comment by dikshajaiswal855** [comment]
Screenshot (2254)
Screenshot (2255)
Screenshot (2256)
@rishicds please tell is this correct or not

**Review by codewarnab — APPROVED** [review]

**Comment by dikshajaiswal855** [comment]
Screenshot (2257)
Screenshot (2258)
Screenshot (2259)
hey @rishicds waiting for your reply

**Comment by dikshajaiswal855** [comment]
Thankyou @codewarnab for your approval

**Comment by rishicds** [comment]
Merged! @dikshajaiswal855 good job

**Comment by dikshajaiswal855** [comment]
Thankyou @rishicds

**Pull request merged**
