### PR TITLE
Remove Scroll From Home Page For Mobile Screen

### PR DESCRIPTION
**Pull request by yash28goyal**
## Description
I have removing the scroll in y direction for mobile because it is not looking good for mobile view.

## Screenshots / GIFs (if applicable)
Paws - Google Chrome 2024-05-31 13-28-58

## Checklist:
- [X] I have performed a self-review of my code
- [ ] I have added/updated relevant documentation (if needed)
- [X] I have tested the changes locally and they function as expected
- [X] I have ensured my code follows the project's coding standards

## Additional Notes
The changes I made have definitely good user experience.

### CODE REVIEW

**Review by codewarnab — CHANGES_REQUESTED** [review]
remove the css from app.css and put in the home page inline or tailwind (preferred)

**Comment by yash28goyal** [comment]
Please review I will add tailwind css in the code.

**Comment by yash28goyal** [comment]
Please review this.

**Comment by codewarnab** [comment]
> Please review this.

I am little busy will review it tomorrow

**Comment by codewarnab** [comment]
there is some parsing error reproduce by doing npm start

**Pull request closed without merging**
