### PR TITLE
made login page responsive

### LINKED ISSUE #261: login page

### PR DESCRIPTION
**Pull request by Rehan52004**
## Description
Making the Login Page Responsive

fixes #261 

## Screenshots / GIFs (if applicable)
paws-3

## Checklist:
- [Yes] I have performed a self-review of my code
- [] I have added/updated relevant documentation (if needed)
- [Yes ] I have tested the changes locally and they function as expected
- [YEs] I have ensured my code follows the project's coding standards

### CODE REVIEW

**Comment by codewarnab** [comment]
add a desktop ss too

**Comment by Rehan52004** [comment]
Screenshot : 

Top:
paws-5
Bottom:
paws-6

Center:
paws-4

**Review by codewarnab — APPROVED** [review]

**Comment by rishicds** [comment]
Fix merfe conflicts pls @Rehan52004

**Comment by Rehan52004** [comment]
Check merge conflicts resolved.

**Review by rishicds — APPROVED** [review]

**Comment by rishicds** [comment]
Fix conflicts and itll be merged @Rehan52004

**Comment by Rehan52004** [comment]
@rishicds check merge conflicts resolved.

**Pull request merged**
