### PR TITLE
Added Preloader

### LINKED ISSUE #497: 💡[FEATURE]: Add Preloader
**Is your feature request related to a problem? Please describe.**
Yes, the absence of a preloader can lead to a poor user experience as users may not understand whether the application is working or not while content is being loaded. This can cause frustration and potentially lead to users abandoning the application. A preloader helps to keep users engaged by providing a visual indication that content is loading.

**Describe the solution you'd like**
**Design and Appearance:**
1. A simple and visually appealing animation.
2. Should match the overall design language of the application.
3. Customizable options for color, size, and style to fit different themes.

**Functionality:**
1. Should display during the loading of heavy components or data fetching processes.
2. Must cover the main content area that is being loaded.
3. Option to show the preloader globally (entire screen) or locally (specific component).

**Performance:**
1. Lightweight and optimized to prevent additional load times.
2. Should not interfere with the loading process of the main content.

**Implementation:**
1. Should be implemented as a reusable component.
2. Easy to integrate with different parts of the application.
3. Must include appropriate documentation for usage and customization.

**Describe alternatives you've considered**
1. Skeleton Screens: Instead of a preloader animation, skeleton screens can be used to display a placeholder for content that is loading. This approach can be less distracting and provide a more seamless experience.
2. Progress Bars: Another alternative is to use a progress bar that shows the percentage of content loaded. This can provide more detailed feedback to users about the loading process.
3. Lazy Loading Indicators: For sections of content that load as the user scrolls, implementing lazy loading indicators can also serve as an alternative to a full preloader.

**Additional context**
My Previous Work:-
https://github.com/Innovateninjas/Paws-frontend/assets/146121869/1bfea191-a76d-467c-8704-2807a0aab031

### PR DESCRIPTION
**Pull request by AsmitaMishra24**
## Description
I have added a preloader for the initial loading.

## Related Issue
fixes #497 

## Screenshots / GIFs (if applicable)
https://github.com/Innovateninjas/Paws-frontend/assets/146121869/78f934eb-677d-4841-aeaf-453ef4c5b215

## Checklist:
- [X] I have performed a self-review of my code
- [ ] I have added/updated relevant documentation (if needed)
- [X] I have tested the changes locally and they function as expected
- [X] I have ensured my code follows the project's coding standards

### CODE REVIEW

**Comment by AsmitaMishra24** [comment]
@codewarnab, please review the pr

**Comment by AsmitaMishra24** [comment]
@codewarnab, please review the pr

**Comment by AsmitaMishra24** [comment]
@codewarnab, Please review the PR. If any changes are needed, let me know and I will make them.

**Comment by AsmitaMishra24** [comment]
@codewarnab, Please review the PR. If any changes are needed, let me know and I will make them.

**Comment by codewarnab** [comment]
resolve the conflict , and tag me again

**Comment by AsmitaMishra24** [comment]
> resolve the conflict , and tag me again

@codewarnab, done

**Comment by codewarnab** [comment]
again please fix

**Comment by AsmitaMishra24** [comment]
> again please fix

done

**Pull request merged**
