### PR TITLE
added a no report is in progress

### PR DESCRIPTION
**Pull request by Abhinavpatra**
## Related Issue
#235 

## Screenshots / GIFs (if applicable)
[Attach any relevant screenshots or GIFs demonstrating the changes]

## Checklist:
- [ x] I have performed a self-review of my code
- [x ] I have added/updated relevant documentation (if needed)
- [ ] I have tested the changes locally and they function as expected
- [x ] I have ensured my code follows the project's coding standards

### CODE REVIEW

**Comment by codewarnab** [comment]
can you please add screenshot of your work

**Comment by Abhinavpatra** [comment]
i am traveling at the moment after my college exams, it will take around 2 more days to get home, i can send the screenshots then, Thanks for your patience!

**Comment by codewarnab** [comment]
> i am traveling at the moment after my college exams, it will take around 2 more days to get home, i can send the screenshots then, Thanks for your patience!

its been 3 days

**Comment by Abhinavpatra** [comment]
sorry, but i can't seem to set up the cloudinary, you should assign this to someone else

**Pull request closed without merging**
