### PR TITLE
Implemented Email verification system before user registration

### PR DESCRIPTION
**Pull request by atharvarekhawar**
## Description
I have used services like Email.js and npm package reat-otp-input to implement the email verification system before user registrstion

## Related Issue
this PR solves issue #270 

## Screenshots / GIFs (if applicable)

https://github.com/Innovateninjas/Paws-frontend/assets/113119063/3e35677d-7a54-434e-a4f5-c475b402f051

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
You have to add your email.js creadentials in .env file to make the functionality work and please add appropriate labels on the PR, Thank you 😊.

### CODE REVIEW

**Comment by atharvarekhawar** [comment]
@codewarnab plz review my PR.

**Comment by atharvarekhawar** [comment]
@codewarnab I have solved merge conflicts , please merge the PR

**Comment by codewarnab** [comment]
> @codewarnab I have solved merge conflicts , please merge the PR

good job man

**Comment by codewarnab** [comment]
i have reversted the pr  please update the contributuion md also add a detailed setup for the envs  you added

**Comment by codewarnab** [comment]
@atharvarekhawar  hey man give the pr aagain with the chanages 

> i have reversted the pr please update the contributuion md also add a detailed setup for the envs you added

hey man give the pr again with this chanages again assap

**Pull request merged**
