### PR TITLE
New Baclground images added in report page

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Description
New Baclground images added in report page

## Related Issue
#381 solved

## Screenshots / GIFs (if applicable)
image
in mobile view
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
[Add any additional notes or context about the changes made]

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
hi @codewarnab please check

**Review by codewarnab — APPROVED** [review]

**Comment by RamakrushnaBiswal** [comment]
@codewarnab add assigns and lebels to the project 🥲

**Comment by codewarnab** [comment]
if you haven't got point for any of the pr you got merged .
dm me on linked in with the pr number you dont get points or all the prs of the repo we will try to contact organizer asap

**Comment by RamakrushnaBiswal** [comment]
in this PR i did not get points @codewarnab

**Comment by codewarnab** [comment]
> in this PR i did not get points @codewarnab

ok noted

**Pull request merged**
