### PR TITLE
#279 contact information page  made responsive

### PR DESCRIPTION
**Pull request by Riddhi162**
## Description
[Please include a brief description of the changes or features added]
I have made the contact details page completely responsive.For all the screens it is responsive.

## Related Issue
#279 

## Screenshots / GIFs (if applicable)
[Attach any relevant screenshots or GIFs demonstrating the changes]
BEFORE:
Screenshot 2024-05-15 020112
AFTER:
Screenshot 2024-05-14 234249

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
[Add any additional notes or context about the changes made]

### CODE REVIEW

**Comment by rishicds** [comment]
Hi, please make the size of both buttons same, otherwise good work, itll be merged after that, also is it responsive on desktop?

**Comment by codewarnab** [comment]
@Riddhi162 add screenshot for desktop

**Review by rishicds — CHANGES_REQUESTED** [review]
Hi @Riddhi162 please update your branch and attach a screenshot of desktop

**Comment by Riddhi162** [comment]
> @Riddhi162 add screenshot for desktop

Sure

**Comment by Riddhi162** [comment]
> Hi @Riddhi162 please update your branch and attach a screenshot of desktop

I edited the files here only and made the button size similar.Please check the commits.

**Comment by codewarnab** [comment]
> > @Riddhi162 add screenshot for desktop
> 
> Sure
> Screenshot 2024-05-17 004141
> Screenshot 2024-05-17 005645
> 
> 
> I also made the button size same
> 
> 

I think if you if you increase the width to 60% of the width of the  div it will looks good and some increase in height in desktop also and font size in the input filed+placeholder please try this and show us how it's looking

**Comment by codewarnab** [comment]
> > > @Riddhi162 add screenshot for desktop
> > 
> > Sure
> > Screenshot 2024-05-17 004141
> > Screenshot 2024-05-17 005645
> > 
> > 
> > I also made the button size same
> > 
> > 
> 
> I think if you if you increase the width to 60% of the width of the  div it will looks good and some increase in height in desktop also and font size in the input filed+placeholder please try this and show us how it's looking 

Also make the buttons bigger and add space between them in desktop

**Comment by Riddhi162** [comment]
> > > @Riddhi162 add screenshot for desktop
> > 
> > 
> > Sure
> > Screenshot 2024-05-17 004141
> > Screenshot 2024-05-17 005645
> > I also made the button size same
> 
> I think if you if you increase the width to 60% of the width of the div it will looks good and some increase in height in desktop also and font size in the input filed+placeholder please try this and show us how it's looking

whose wiidth should i make to 60% the input field or its outer div?

**Comment by codewarnab** [comment]
> > > > @Riddhi162 add screenshot for desktop
> > > 
> > > 
> > > Sure
> > > Screenshot 2024-05-17 004141
> > > Screenshot 2024-05-17 005645
> > > I also made the button size same
> > 
> > 
> > I think if you if you increase the width to 60% of the width of the div it will looks good and some increase in height in desktop also and font size in the input filed+placeholder please try this and show us how it's looking
> 
> whose wiidth should i make to 60% the input field or its outer div?

no leave it just make the buttons bigger and add space between them for desktop

**Comment by Riddhi162** [comment]
> > > > > @Riddhi162 add screenshot for desktop
> > > > 
> > > > 
> > > > Sure
> > > > Screenshot 2024-05-17 004141
> > > > Screenshot 2024-05-17 005645
> > > > I also made the button size same
> > > 
> > > 
> > > I think if you if you increase the width to 60% of the width of the div it will looks good and some increase in height in desktop also and font size in the input filed+placeholder please try this and show us how it's looking
> > 
> > 
> > whose wiidth should i make to 60% the input field or its outer div?
> 
> no leave it just make the buttons bigger and add space between them for desktop and solve the conflicts

Done.

**Comment by Riddhi162** [comment]
> Hi @Riddhi162 please update your branch and attach a screenshot of desktop

Done.

**Comment by codewarnab** [comment]
> > > > > > @Riddhi162 add screenshot for desktop
> > > > > 
> > > > > 
> > > > > Sure
> > > > > Screenshot 2024-05-17 004141
> > > > > Screenshot 2024-05-17 005645
> > > > > I also made the button size same
> > > > 
> > > > 
> > > > I think if you if you increase the width to 60% of the width of the div it will looks good and some increase in height in desktop also and font size in the input filed+placeholder please try this and show us how it's looking
> > > 
> > > 
> > > whose wiidth should i make to 60% the input field or its outer div?
> > 
> > 
> > no leave it just make the buttons bigger and add space between them for desktop and solve the conflicts
> 
> Done.

can you please add another screenshot how its looking now for mobile and desktop

**Comment by Riddhi162** [comment]
Screenshot 2024-05-20 003302
Screenshot 2024-05-20 003322

**Comment by codewarnab** [comment]
> Screenshot 2024-05-20 003302
> Screenshot 2024-05-20 003322
> 

I told you to add space in the desktop mode not in the mobile , also buttons are looking smaller than before in mobile

**Comment by Riddhi162** [comment]
image
Okay made the changes for mobile view

**Comment by codewarnab** [comment]
thank you good job  will be merged soon

**Review by codewarnab — APPROVED** [review]

**Comment by codewarnab** [comment]
@rishicds

**Pull request merged**
