### PR TITLE
Error

### PR DESCRIPTION
**Pull request by taneeshaa15**
Screenshot from 2024-07-04 22-24-52

Hi @codewarnab  ,
I hope you're doing well. I've addressed the issue #512  and created a pull request to resolve it.
Could you please review the PR and let me know if any adjustments are needed?

Best regards,
Tanisha Garg

## Summary by CodeRabbit

- **New Features**
	- Introduced a user-friendly `NotFoundPage` for handling 404 errors, enhancing navigation experience.
	- Added a new script for starting the development server (`"dev": "vite"`), streamlining the development workflow.

- **Bug Fixes**
	- Updated viewport meta tag for improved mobile rendering consistency.

- **Style**
	- Enhanced application styling with refined CSS rules for various components, improving overall visual appeal and layout.

- **Documentation**
	- Improved comments and code clarity in the main application component; adjustments made for better readability and maintainability.

### CODE REVIEW

**Comment by taneeshaa15** [comment]
@codewarnab Please review.

**Comment by taneeshaa15** [comment]
@codewarnab Please review.

**Comment by taneeshaa15** [comment]
@codewarnab Please review asap.

**Comment by codewarnab** [comment]
we only perefer tailwind for this type of pages not css at max inline css is ok , and also file name should be not found not error page , try to create a fresh fork and put your chanages theri ( tailwind only)

**Comment by taneeshaa15** [comment]
Okay, May you please tell me that whether that UI is fine or I need to change that too.

**Comment by taneeshaa15** [comment]
@codewarnab Here is the updated Not Found Page which is made by using tailwind css, Please have a look

[Screencast from 2024-07-09 23-04-31.webm](https://github.com/Innovateninjas/Paws-frontend/assets/157527085/85310b05-609e-456f-a0bd-b8a5aa06f731)

**Comment by taneeshaa15** [comment]
@codewarnab Please review it.

**Comment by codewarnab** [comment]
will review it tommorow

**Pull request merged**
