### PR TITLE
Made user registration page responsive under #271

### PR DESCRIPTION
**Pull request by Priyal208**
## Description
User registration page was made responsive under issue assigned to me #271 , i made it responsive using tailwind, fixed margin and padding , made form and image appear in row in mobile view and coloumn in desktop view, adjusted font size for different devices
I did remove image of dog in mobile view as you told me so

## Related Issue
Related to #252 and part of #242 
GSsoc #271

## Screenshots / GIFs (if applicable)
BEFORE(MOBILE VIEW):
Screenshot 2024-05-29 004417
Screenshot 2024-05-29 004435

AFTER(MOBILE AND DESKTOP VIEW) : 
Screenshot 2024-05-28 232355
Screenshot 2024-05-29 113843

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
I deleted old PR and forked new one as you told me since it had earlier commits

### CODE REVIEW

**Comment by codewarnab** [comment]
good job

**Review by codewarnab — APPROVED** [review]

**Review by rishicds — APPROVED** [review]

**Comment by rishicds** [comment]
fix conflicts @Priyal208

**Comment by rishicds** [comment]
fix the conflicts please @Priyal208

**Comment by Priyal208** [comment]
yes

**Comment by Priyal208** [comment]
done @rishicds

**Comment by rishicds** [comment]
good job @Priyal208

**Comment by Priyal208** [comment]
thank you

**Comment by atharvarekhawar** [comment]
Hello @rishicds this code is broken please review it once and revert the changes

**Comment by codewarnab** [comment]
> Hello @rishicds this code is broken please review it once and revert the changes

right

**Pull request merged**
