### PR TITLE
[Feature] : Implement the Button animation and transition

### PR DESCRIPTION
**Pull request by sivaprasath2004**
## Description
#293 feature can be added..

## Related Issue
New Feature like button transition and button `box-shadow` and hover

## Screenshots / GIFs (if applicable)
[Screencast from 2024-05-13 16-45-31.webm](https://github.com/Innovateninjas/Paws-frontend/assets/121082414/d051f91c-9ccd-4802-ae73-039854bb1a53)

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@codewarnab I will finish it..... :rocket:

**Comment by rishicds** [comment]
Hi @sivaprasath2004 , please fix the conflicts , also if possible change the color of the button to green and make the animation less intrusive so it matches the theme, otherwise its good

**Comment by sivaprasath2004** [comment]
@rishicds i will finished it..

**Comment by codewarnab** [comment]
@sivaprasath2004 add the scrrenshot . btw button colour should be  green add some subtle animation not much animation needed .

**Comment by sivaprasath2004** [comment]
@codewarnab  I will finish it..


[Screencast from 2024-05-16 19-06-51.webm](https://github.com/Innovateninjas/Paws-frontend/assets/121082414/a790940a-f821-4e12-8515-59cf2e1952df)

**Comment by codewarnab** [comment]
@sivaprasath2004 it looks good but you have used lots of external css we encourage using tailwind css try to chanage those as much in tailwind you can we :) 
also whats in the app.css do ? their is already a button.css is their , and share a gif showing that reactivity of the button is same as before which shows waiting, loggin in etc during the login and registration . Thank you

**Comment by sivaprasath2004** [comment]
Hello @codewarnab I can try to change `tailwind css` but that cannot expected work that is inproper so i suggest external css that is proper work please proceed or change to the another model button animation.

**Comment by codewarnab** [comment]
> Hello @codewarnab I can try to change `tailwind css` but that cannot expected work that is inproper so i suggest external css that is proper work please proceed or change to the another model button animation.

you didnt answered another question what the styles in app.css do ? 
we dont prefer writing styles in app.css until its used in many files

**Comment by codewarnab** [comment]
@sivaprasath2004 reply asap else we have to close this pr

**Pull request closed without merging**
