### PR TITLE
Fixed: Made OUR TEAM page responsive.

### LINKED ISSUE #378: 🪲[Bug]: "OUR TEAM" page is not responsive.
**Describe the bug**
"Our Team" page is not responsive in all devices, The content is being overflown.

**To Reproduce**
1. Go to donations page.
2. Click on Crew link.
3. Our page page will come.

**Expected behavior**
By changing and adding the styling to the code, we can achieve responsiveness.

**Screenshots**
Screenshot 2024-05-21 200116
Mobile view:
Screenshot 2024-05-21 200012

**Desktop (please complete the following information):**
 - OS: HP (Android)
 - Browser : Chrome
 - Version : Latest version

**Smartphone (please complete the following information):**
 - Device: Vivo IQOO
 - OS: Funtouch OS
 - Browser : Chrome
 - Version: Latest version

**Additional context**
Please assign me this issue , I would like to contribute to this project under GSSoC'24.

### PR DESCRIPTION
**Pull request by nagalakshmi08**
## Description
Made the changes in OUR TEAM page and made it responsive. Now the cards will not overflow and look good.

## Related Issue
Fixes #378 

## Screenshots / GIFs (if applicable)
Screenshot (258)
 
In mobile:
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

### CODE REVIEW

**Review by codewarnab — APPROVED** [review]

**Comment by codewarnab** [comment]
can you add a screenshot of `npm run build` its succesfull building or not

**Comment by nagalakshmi08** [comment]
> can you add a screenshot of `npm run build` its succesfull building or not

Yeah sure.. 
image

**Comment by codewarnab** [comment]
Approved will be merged soon

**Comment by nagalakshmi08** [comment]
Hi @codewarnab , @rishicds .. Could you please add the GSSoC and level labels to this issue and PR to include it under GSSoC '24.

**Pull request merged**
