### PR TITLE
Navbar position change

### PR DESCRIPTION
**Pull request by Parimalasri13**
changed the position of navbar

### CODE REVIEW

**Review by DEV-Soumya-Ranjan-Swain — COMMENTED** [review]
this changes the position of the navbar from bottom to top, but there is no issue associated with this pr.

**Comment by Parimalasri13** [comment]
@DEV-Soumya-Ranjan-Swain  can you please check this issue  (navbar position is bad #250 )

**Review by DEV-Soumya-Ranjan-Swain — APPROVED** [review]
ok this does change the positioning of the navbar from bottom to top

**Comment by codewarnab** [comment]
@Parimalasri13 please screenshot of your work

**Comment by codewarnab** [comment]
you changed postion from bottom to top so how will use the nav bar when using a phone ? rather keep the nav bar as it is

**Pull request closed without merging**
