### PR TITLE
fixed the issue #323

### PR DESCRIPTION
**Pull request by shreyash776**
## Description
[add the confirm password field in the register page and implemented the logic to check the entered password]

## Related Issue
[issue #323]

## Screenshots / GIFs (if applicable)
[Attach any relevant screenshots or GIFs demonstrating the changes]

## Checklist:
- [ yes] I have performed a self-review of my code
- [yes ] I have added/updated relevant documentation (if needed)
- [yes ] I have tested the changes locally and they function as expected
- [yes ] I have ensured my code follows the project's coding standards

### CODE REVIEW

**Comment by codewarnab** [comment]
@shreyash776  i think you have mistakenly deleted the  package-lock.json please restore it and commit

**Comment by rishicds** [comment]
Please fix merge conflicts, it will be merged after that.

**Comment by rishicds** [comment]
image


Hi, please make it responsive

**Comment by codewarnab** [comment]
@shreyash776 just noticed issue is not assigned to you . this is not how it works gssoc assigns works on first come first serve basis and the author of the issue creartor mentioned that he/she want to work on that i have to assigne him/her . so please comment their

**Pull request closed without merging**
