### PR TITLE
fix: styling for compaign page

### LINKED ISSUE #460: 💡[FEATURE]: Compaign Page Background Styles
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I see super bright light in front of me on the web, those bright lights stun my eyes as its very difficult for people with dry eyes to read the text at the light theme,

**Describe the solution you'd like**
In continuation to my query, I would like to add styling to the compaign page

**Additional context**
Screenshot 2024-06-04 124248
Screenshot 2024-06-04 124304

Please mark appropriate gssoc label and level so that I can start working on this issue, It would need some research and time for getting inside the code and find the areas where dark mode can be applied...

### PR DESCRIPTION
**Pull request by anisharma07**
## Description
The compaign post page styling is restored with the older bluish styles ... had to check out previous versions of paws, install it, run it and look for the code.

## Related Issue
fixes #460

## Screenshots / GIFs (if applicable)
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have added/updated relevant documentation (if needed)
- [x] I have tested the changes locally and they function as expected
- [x] I have ensured my code follows the project's coding standards

## Additional Notes
Please Assign Appropriate GSSoC label and level.
Also assign me the above issue and mark labels to it, if you are merging this PR...

### CODE REVIEW

**Comment by codewarnab** [comment]
image
i want to see how its look with that image in the background .

**Comment by codewarnab** [comment]
if  you change anything in the Background component it will chanage many pages background which i dont want

**Comment by anisharma07** [comment]
image
image
image

I changed back the background component to that dog png image and replaced the origin css with background component..in campaign post page...

**Review by codewarnab — APPROVED** [review]

**Comment by anisharma07** [comment]
> Reference

I have resolved all the conflicts....
FILE CHANGES: 

1>> background image URL to use absolute URL rather than relative.....
image

2>> compaign post background component removed and added the bluish background gradient...
image

**Comment by codewarnab** [comment]
we are moved to vite can you update your branc accordingly ( prefer creating a new fork and put your chanages their )

**Comment by anisharma07** [comment]
> we are moved to vite can you update your branc accordingly ( prefer creating a new fork and put your chanages their )

@codewarnab Are you talking about another PR from other new branch? .... (how can i fork twice though? )

**Comment by codewarnab** [comment]
> > we are moved to vite can you update your branc accordingly ( prefer creating a new fork and put your chanages their )
> 
> @codewarnab Are you talking about another PR from other new branch? .... (how can i fork twice though? )

yeah fresh new branch ( by changing name while forking )

**Pull request closed without merging**
